# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 21))
        self.menubar.setObjectName("menubar")
        self.menuCari_lemleri = QtWidgets.QMenu(self.menubar)
        self.menuCari_lemleri.setObjectName("menuCari_lemleri")
        self.menuStoklar = QtWidgets.QMenu(self.menubar)
        self.menuStoklar.setObjectName("menuStoklar")
        self.menuGiri_Fi_i_i_lemleri = QtWidgets.QMenu(self.menubar)
        self.menuGiri_Fi_i_i_lemleri.setObjectName("menuGiri_Fi_i_i_lemleri")
        self.menu_k_Fi_i_lemleri = QtWidgets.QMenu(self.menubar)
        self.menu_k_Fi_i_lemleri.setObjectName("menu_k_Fi_i_lemleri")
        self.menuStok_Haraketleri = QtWidgets.QMenu(self.menubar)
        self.menuStok_Haraketleri.setObjectName("menuStok_Haraketleri")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCariler = QtWidgets.QAction(MainWindow)
        self.actionCariler.setObjectName("actionCariler")
        self.actionCari_Ekle = QtWidgets.QAction(MainWindow)
        self.actionCari_Ekle.setObjectName("actionCari_Ekle")
        self.actionCari_Bul = QtWidgets.QAction(MainWindow)
        self.actionCari_Bul.setObjectName("actionCari_Bul")
        self.actionStoklar = QtWidgets.QAction(MainWindow)
        self.actionStoklar.setObjectName("actionStoklar")
        self.actionStok_ekle = QtWidgets.QAction(MainWindow)
        self.actionStok_ekle.setObjectName("actionStok_ekle")
        self.actionGiri_Fi_i = QtWidgets.QAction(MainWindow)
        self.actionGiri_Fi_i.setObjectName("actionGiri_Fi_i")
        self.actionYap_lan_Giri_Fi_leri = QtWidgets.QAction(MainWindow)
        self.actionYap_lan_Giri_Fi_leri.setObjectName("actionYap_lan_Giri_Fi_leri")
        self.action_k_Fi_i = QtWidgets.QAction(MainWindow)
        self.action_k_Fi_i.setObjectName("action_k_Fi_i")
        self.actionYap_lan_k_fi_leri = QtWidgets.QAction(MainWindow)
        self.actionYap_lan_k_fi_leri.setObjectName("actionYap_lan_k_fi_leri")
        self.actionStok_Haraket_Takip = QtWidgets.QAction(MainWindow)
        self.actionStok_Haraket_Takip.setObjectName("actionStok_Haraket_Takip")
        self.menuCari_lemleri.addAction(self.actionCariler)
        self.menuCari_lemleri.addAction(self.actionCari_Ekle)
        self.menuCari_lemleri.addAction(self.actionCari_Bul)
        self.menuStoklar.addAction(self.actionStoklar)
        self.menuStoklar.addAction(self.actionStok_ekle)
        self.menuGiri_Fi_i_i_lemleri.addAction(self.actionGiri_Fi_i)
        self.menuGiri_Fi_i_i_lemleri.addAction(self.actionYap_lan_Giri_Fi_leri)
        self.menu_k_Fi_i_lemleri.addAction(self.action_k_Fi_i)
        self.menu_k_Fi_i_lemleri.addAction(self.actionYap_lan_k_fi_leri)
        self.menuStok_Haraketleri.addAction(self.actionStok_Haraket_Takip)
        self.menubar.addAction(self.menuCari_lemleri.menuAction())
        self.menubar.addAction(self.menuStoklar.menuAction())
        self.menubar.addAction(self.menuGiri_Fi_i_i_lemleri.menuAction())
        self.menubar.addAction(self.menu_k_Fi_i_lemleri.menuAction())
        self.menubar.addAction(self.menuStok_Haraketleri.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuCari_lemleri.setTitle(_translate("MainWindow", "Cari İşlemleri"))
        self.menuStoklar.setTitle(_translate("MainWindow", "Stok işlemleri"))
        self.menuGiri_Fi_i_i_lemleri.setTitle(_translate("MainWindow", "Giriş Fişi işlemleri"))
        self.menu_k_Fi_i_lemleri.setTitle(_translate("MainWindow", "Çıkış Fişi İşlemleri"))
        self.menuStok_Haraketleri.setTitle(_translate("MainWindow", "Stok Haraketleri"))
        self.actionCariler.setText(_translate("MainWindow", "Cariler"))
        self.actionCari_Ekle.setText(_translate("MainWindow", "Cari Ekle"))
        self.actionCari_Bul.setText(_translate("MainWindow", "Cari Bul"))
        self.actionStoklar.setText(_translate("MainWindow", "Stoklar"))
        self.actionStok_ekle.setText(_translate("MainWindow", "Stok ekle"))
        self.actionGiri_Fi_i.setText(_translate("MainWindow", "Giriş Fişi"))
        self.actionYap_lan_Giri_Fi_leri.setText(_translate("MainWindow", "Yapılan Giriş Fişleri"))
        self.action_k_Fi_i.setText(_translate("MainWindow", "Çıkış Fişi"))
        self.actionYap_lan_k_fi_leri.setText(_translate("MainWindow", "Yapılan Çıkış Fişleri"))
        self.actionStok_Haraket_Takip.setText(_translate("MainWindow", "Stok Haraket Takip"))
